### ISSUE TITLE
Larger Font Size

### ISSUE THREAD

**Issue by mody823** [O-RONI/TrueWin11Dark#1]
i would really like to make the font sizer a bit larger cause I find it too small for me

**Comment by okrroni** [comment]
Hi, are you using the 1.19 version of Flow Launcher?

It seems that the size of the main elements (including font size) are now managed by the settings in the _Appearance_ section. Adjusting this values can solve your problem.

![image](https://github.com/user-attachments/assets/36d2c403-1ec7-4a9d-9971-fbbb074dc6da)

**Comment by mody823** [comment]
Yeah, Flow Launcher changed after 1.19 update, Thanks for the help
